// <auto-generated />
using MagazynApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazynApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagazynApp.Domain.Entities.Kontrahent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kontrahenci");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Lokalizacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyRozladunek")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZaladunek")
                        .HasColumnType("bit");

                    b.Property<int>("MagazynId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MagazynId");

                    b.ToTable("Lokalizacje");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Magazyn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaksLokalizacji")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Magazyny");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Przedmiot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DostawcaId")
                        .HasColumnType("int");

                    b.Property<int>("LokalizacjaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdbiorcaId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DostawcaId");

                    b.HasIndex("LokalizacjaId");

                    b.HasIndex("OdbiorcaId");

                    b.ToTable("Przedmioty");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Lokalizacja", b =>
                {
                    b.HasOne("MagazynApp.Domain.Entities.Magazyn", "Magazyn")
                        .WithMany("Lokalizacje")
                        .HasForeignKey("MagazynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Przedmiot", b =>
                {
                    b.HasOne("MagazynApp.Domain.Entities.Kontrahent", "Dostawca")
                        .WithMany()
                        .HasForeignKey("DostawcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MagazynApp.Domain.Entities.Lokalizacja", "Lokalizacja")
                        .WithMany("Przedmioty")
                        .HasForeignKey("LokalizacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazynApp.Domain.Entities.Kontrahent", "Odbiorca")
                        .WithMany()
                        .HasForeignKey("OdbiorcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dostawca");

                    b.Navigation("Lokalizacja");

                    b.Navigation("Odbiorca");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Lokalizacja", b =>
                {
                    b.Navigation("Przedmioty");
                });

            modelBuilder.Entity("MagazynApp.Domain.Entities.Magazyn", b =>
                {
                    b.Navigation("Lokalizacje");
                });
#pragma warning restore 612, 618
        }
    }
}
